# Generated by Django 2.2.13 on 2020-08-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('limit', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('cellphone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMember',
            fields=[
                ('study_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='study_members',
            field=models.ManyToManyField(through='api.StudyMember', to='api.User'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateField()),
                ('place', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Study')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPicture',
            fields=[
                ('activity_picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Study')),
            ],
        ),
    ]
