# Generated by Django 2.2.13 on 2020-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
