# Generated by Django 2.2.13 on 2020-09-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_flag',
            field=models.BooleanField(default=True),
        ),
    ]
