# Generated by Django 2.2.13 on 2020-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimage',
            name='id',
        ),
        migrations.AddField(
            model_name='testimage',
            name='image_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
