# Generated by Django 2.2.13 on 2020-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200907_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimage',
            name='image_id',
        ),
        migrations.AddField(
            model_name='testimage',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
