# Generated by Django 2.2.13 on 2020-09-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200904_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='s3_profile_img',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
