# Generated by Django 2.2.13 on 2020-08-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200806_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-datetime']},
        ),
    ]
