# Generated by Django 2.2.13 on 2020-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200811_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
