# Generated by Django 2.2.13 on 2020-08-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='address',
        ),
    ]
