# Generated by Django 2.2.13 on 2020-09-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_img',
            new_name='s3_profile_img',
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_profile_img',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
