# Generated by Django 2.2.13 on 2020-09-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200904_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_flag',
            field=models.BooleanField(default=True),
        ),
    ]
