# Generated by Django 2.1 on 2020-07-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisestudy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitypicture',
            old_name='study_id',
            new_name='study',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='study_id',
            new_name='study',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='studymember',
            old_name='study_id',
            new_name='study',
        ),
        migrations.RenameField(
            model_name='studymember',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='user_id',
            new_name='user',
        ),
    ]
