# Generated by Django 2.1 on 2020-07-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisestudy_app', '0002_auto_20200722_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
